.old/Class works/Django_example/untitled1/untitled1/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from main.views import MainView, VolonterListView, VolonterDetailView, VolonterCreateView, VolonterUpdateView, ChangeConvictionsView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^test/', MainView.as_view()),
    url(r'^$', MainView.as_view()),
    url(r'^volonters/',
        VolonterListView.as_view(),
        name='list_volonters'),
    url(r'^volonter/(?P<pk>\d+)/$',
        VolonterDetailView.as_view(),
        name='view_volonter'),
    url(r'^volonter/add/',
        VolonterCreateView.as_view(),
        name='create_volonter'),
    url(r'^volonter/(?P<pk>\d+)/edit/',
        VolonterUpdateView.as_view(),
        name='update_volonter'),

    url(r'^actions/change_convictions/(?P<volonter_id>\d+)/',
        ChangeConvictionsView.as_view(),
        name='change_convictions')
]

.old/Home works/Konstantin_Ya/untitled4/untitled4/urls.py
from unicodedata import name
from django.conf.urls import include, url
from django.contrib import admin
from Resource.views import MainView, ResourceListView, ResourceDetailView, ResourceCreateView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^test/', MainView.as_view()),
    url(r'^Resource/$',
        ResourceListView.as_view(),
        name='list_resource'),
    url(r'^Resource/(?P<pk>\d+)/$',
        ResourceDetailView.as_view(),
        name = 'view_resource'),
    url (r'^Resource/add/$',
         ResourceCreateView.as_view(),
         name = 'create_resource'),
]

.old/Home works/Kornienko A/mypj/mypj/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from main.views import MainView,OrderView, VolonterListView,VolonterGrafikView, VolonterDetailView, VolonterCreateView, OrderDetailView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls),name='admins'),
    url(r'^test/', MainView.as_view()),
    url(r'^$', MainView.as_view()),
    url(r'^volonters/',
        VolonterListView.as_view(),
        name='list_volonters'),
    url(r'^volonter/(?P<pk>\d+)/$',
        VolonterDetailView.as_view(),
        name='view_volonter'),
    url(r'^volonter/add/$',
        VolonterCreateView.as_view(),
        name='create_volonter'),
     url(r'^orders/$',
        OrderView.as_view(),
        name='order_list'),
    url(r'^orders/(?P<pk>\d+)/$',
        OrderDetailView.as_view(),
        name='view_order'),
    url(r'^volonter/grafik/$',
        VolonterGrafikView.as_view(),
        name = 'grafic_volonter',
        )

]

db_volonters/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout
from main.views import MainView, VolonterListView, VolonterDetailView, VolonterCreateView, VolonterGrafikView, \
    CreateVolontersView, ResourceGrafikView, CreateNeedsView, CreatePointOfConsumingView,FinishedView, \
    ResourceListView, DeleteCandidateVolonterView, ActivateCandidateVolonterView,MoneyView, GraphView, \
    CreateOrderView, NeedListView, NeedCreateView, MapView, AboutView, AviceView, RoatView, CreateRoat, \
    GeneralAlgoView, PerListView, FirstAlgoView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^test/$', MainView.as_view()),
    url(r'^$', MainView.as_view(), name='home'),

    url(r'^accounts/profile/$', MainView.as_view(), name='home'),

    url(r'^login/', login, name='login'),
    url(r'^logout/', logout, name='logout'),

    url(r'^Volonter/$',VolonterListView.as_view(), name='list_volonter'),

    url(r'^performance/$',PerListView.as_view(), name='per'),
    url(r'^Volonter/(?P<pk>\d+)/$',VolonterDetailView.as_view(), name='view_volonter'),
    url(r'^Volonter/add/',VolonterCreateView.as_view(), name='create_volonter'),

    url(r'^order/add/$',CreateOrderView.as_view(), name='create_order'),

    url(r'^advice/$',AviceView.as_view(), name='advice'),
    url(r'^map/$',MapView.as_view(), name='map_stores'),
    # url(r'^roat/$',RoatView.as_view(), name='roat'),
    url(r'^roat/(?P<pk>\d+)/$',RoatView.as_view(), name='roat'),
    url(r'^about/$',AboutView.as_view(), name='about'),

    url(r'^need/$',NeedListView.as_view(), name='list_need'),
    url(r'^support/$',AboutView.as_view(), name='about'),
    url(r'^need/add/$',NeedCreateView.as_view(), name='create_need'),

    # url(r'^Volonter/(?P<pk>\d+)/edit/',VolonterUpdateView.as_view(), name='update_volonter'),

    # url(r'^StoreHouse/$',StoreHouseListView.as_view(), name= 'list_StoreHouse'),
    # url(r'^StoreHouse/(?P<pk>\d+)/$', StoreHouseDetailView.as_view(), name='view_StoreHouse' ),
    # url(r'^StoreHouse/add/$', StoreHouseCreateView.as_view(), name='create_StoreHouse' ),
    # url(r'^StoreHouse/(?P<pk>\d+)/edit/', StoreHouseUpdateView.as_view(), name='update_StoreHouse' ),
    #
    # url(r'kwork/', KindOfWorkListView.as_view(), name='list_kindofwork'),
    # url(r'kwork/(?P<pk>\d+)/$', KindOfWorkDetailView.as_view(), name='view_kindofwork'),
    #
    # url(r'skills/', SkillListView.as_view(), name='list_skill'),
    # url(r'skill/(?P<pk>\d+)/$', SkillDetailView.as_view(), name='view_skill'),
    #
    # url(r'transport/', TransportListView.as_view(), name='list_transport'),
    # url(r'transport/(?P<pk>\d+)/$', TransportDetailView.as_view(), name='view_transport'),
    #grafik_recourse

    url(r'^volonter/grafik/$',VolonterGrafikView.as_view(),name = 'grafik_volonter'),
    url(r'^resource/grafik/(?P<pk>\d+)$',ResourceGrafikView.as_view(),name = 'grafik_resource'),

    url(r'^resource/$',
        ResourceListView.as_view(),
        name='list_resource'),
    # url(r'^Resource/(?P<pk>\d+)/$',
    #     ResourceDetailView.as_view(),
    #     name = 'view_resource'),
    # url(r'^Resource/add/$',
    #     ResourceCreateView.as_view(),
    #     name = 'create_resource'),
    #
    # url(r'^Need/$',
    #     NeedListView.as_view(),
    #     name = 'list_need'),
    # url(r'^Need/(?P<pk>\d+)/$',
    #     NeedDetailView.as_view(),
    #     name = 'view_need'),
    # url(r'^Need/add/$',
    #     NeedCreateView.as_view(),
    #     name = 'create_need'),
    #
    # url(r'^PointOfConsuming/$',
    #     PointOfConsumingListView.as_view(),
    #     name = 'list_pointofconsuming'),
    # url(r'^PointOfConsuming/(?P<pk>\d+)/$',
    #     PointOfConsumingDetailView.as_view(),
    #     name = 'view_pointofconsuming'),
    # url(r'^PointOfConsuming/add/$',
    #     PointOfConsumingCreateView.as_view(),
    #     name = 'create_pointofconsuming'),

    url(r'^general_algo/$', GeneralAlgoView.as_view(), name='general_algo'),

    url(r'^actions/finished/(?P<resource_order_id>\d+)/',
        FinishedView.as_view(),
        name='finished'),
    url(r'^test/create_volonters',CreateVolontersView.as_view()),
    url(r'^test/create_needs', CreateNeedsView.as_view()),
    url(r'^test/create_pointofconsuming', CreatePointOfConsumingView.as_view()),
    url(r'response/$',MoneyView.as_view()),
    url(r'graph/$', GraphView.as_view()),
    url(r'^test/create_pointofconsuming', CreatePointOfConsumingView.as_view()),
    url(r'^actions/delete/(?P<volonter_id>\d+)/', DeleteCandidateVolonterView.as_view(), name='delete'),
    url(r'^actions/add/(?P<volonter_id>\d+)',ActivateCandidateVolonterView.as_view(), name='activate'),
    # url(r'^action/map', LeliksView.as_view(), name='leliksview')
    # url(r'actions/revertways/', RevertWayView.as_view()),
    url(r'create_roat', CreateRoat.as_view(), name='create_roat'),
    url(r'algo/$', FirstAlgoView.as_view()),
 ]

.old/Class works/Django_example/untitled1 (old)/main/models.py
# coding: utf-8
from django.db import models

class Volonter(models.Model):
    GENDER_CHOICES = (
        (u'М', 'Male'),
        (u'Ж', 'Female'),
    )
    fio = models.CharField(verbose_name=u'ФИО', max_length=200)
    birthday = models.DateField(null=True, blank=True)
    address = models.TextField()
    telephone = models.CharField(max_length=20)
    gender = models.CharField(max_length=1,
                              choices=GENDER_CHOICES)

    def __unicode__(self):
        return "%s, %s" % (self.fio, self.gender)

class KindOfWork(models.Model):
    name = models.CharField(max_length=100)

class Skill(models.Model):
    volonter = models.ForeignKey('Volonter')
    kind = models.ForeignKey('KindOfWork', null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)

.old/Class works/Django_example/untitled1 (old)/main/views.py
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from main.models import Volonter


class MainView(TemplateView):
    template_name = 'list_volonter.html'

    def get_context_data(self, **kwargs):
        context = super(MainView, self).get_context_data(**kwargs)
        context.update({
            'hello': 'world',
            'volonters': Volonter.objects.all(),
        })
        return context


class VolonterListView(ListView):
    template_name = 'list_volonter.html'
    model = Volonter
    context_object_name = 'volonters'

class VolonterDetailView(DetailView):
    template_name = 'view_volonter.html'
    model = Volonter
    context_object_name = 'volonter'

class VolonterCreateView(CreateView):
    template_name = 'create_volonter.html'
    model = Volonter
    fields = ('fio', 'address',
              'telephone', 'gender')
    success_url = reverse_lazy('list_volonters')

class VolonterUpdateView(UpdateView):
    template_name = 'update_volonter.html'
    model = Volonter
    context_object_name = 'volonter'
    fields = ('fio', 'address',
              'telephone', 'gender')

.old/Class works/Django_example/untitled1 (old)/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>

    <table border="1">
        <tr>
            <td><a href="{% url 'list_volonters' %}">list</a>
                Title: {% block title %}{% endblock %}</td>
        </tr>
        <tr>
            <td>Content: {% block content %}{% endblock %}</td>
        </tr>
    </table>

</body>
</html>

.old/Class works/Django_example/untitled1 (old)/templates/create_volonter.html
{% extends 'base.html' %}

{% block title %}
    <h3>Волонтёр: {{ volonter.fio }}</h3>
{% endblock %}

{% block content %}
    <form method="POST" action="{% url 'create_volonter' %}">
        {% csrf_token %}
        <li>ФИО: <input type="text" name="fio">
        <li>Адрес:<input type="text" name="address">
        <li>Тел:<input type="text" name="telephone">
        <li>Пол:<input type="text" name="gender">
        <input type="submit" value="Save!">
    </form>
{% endblock %}

.old/Class works/Django_example/untitled1 (old)/templates/list_volonter.html
{% extends 'base.html' %}

{% block title %}
    <h3>Список волонтёров</h3>
{% endblock %}

{% block content %}
    Значение переменной "hello": "<i>{{ hello }}</i>"
    <BR/><ol>
    {% for volonter in volonters %}
{#        <a href="/volonter/{{ volonter.id }}/"> #}
        <li><a href="{% url 'view_volonter' volonter.id %}">
                {{ volonter.fio }}
            </a>
            (<a href="{% url 'update_volonter' volonter.id %}">
                edit
            </a>)
        </li>
    {% endfor %}
    </ol>
    <a href="{% url 'create_volonter' %}">
        Add new volonter
    </a>
{% endblock %}

.old/Class works/Django_example/untitled1 (old)/templates/update_volonter.html
{% extends 'base.html' %}

{% block title %}
    <h3>Волонтёр: {{ volonter.fio }}</h3>
{% endblock %}

{% block content %}
    <form method="POST" action="{% url 'update_volonter' volonter.pk %}">
        <li>ФИО: <input type="text" name="fio">
        <li>Адрес:<input type="text" name="address">
        <li>Тел:<input type="text" name="telephone">
        <li>Пол:<input type="text" name="gender">
        <input type="submit" value="Save!">
    </form>
{% endblock %}

.old/Class works/Django_example/untitled1 (old)/templates/view_volonter.html
{% extends 'base.html' %}

{% block title %}
    <h3>Волонтёр: {{ volonter.fio }}</h3>
{% endblock %}

{% block content %}
<ul>
    <li>День рождения:
        {{ volonter.birthday|date:"d.m.Y" }}
    <li>Адрес: {{ volonter.address }}
    <li>Пол: {{ volonter.gender }},
        {{ volonter.get_gender_display }}
</ul>
{% endblock %}